apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lukas666
  namespace: argocd
spec:
  destination:
    namespace: lukas
    server: https://kubernetes.default.svc
  project: default
  source:
    path: guestbook-chart
    targetRevision: master
    repoURL: https://github.com/lukas665/argocd-test.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
